### ISSUE TITLE
Le sort "Sens" n'existe apparemment pas

### ISSUE THREAD

**Issue by brunobord** [lecrapal/lecrapal.github.io#1]
Hello !

Dans la partie des équipements optionnels du Sourcier, j'ai remarqué la ligne suivante 👍 

> Pierre oculaire (Sort : Sens, si placée dans l'eau douce)

Or, le sort "Sens" n'existe pas dans le SRD. Ce qui s'en rapproche le plus est "Sentir" (n°82). En revanche, je ne sais pas lequel des deux est le "bon" nom de sort...

**Comment by lecrapal** [comment]
Encore une fois, bonne remarque.
Sentir serait le plus approprié je pense. Sens est trop vague

Je profite de cette dernière issue pour te demander. Tu préfères corriger tes retours ou je le fais ?

En tout cas merci pour ta relecture et tes retours ;)
