### ISSUE TITLE
Pluriel: "PJ" ou "PJs" ?

### ISSUE THREAD

**Issue by brunobord** [lecrapal/lecrapal.github.io#3]
j'ai relevé une petite incohérence pour le terme abbrévié "PJ". Au pluriel, il est parfois orthographié "PJ", parfois, "PJs". Quelle est la bonne version ?

(note : pour le terme "PNJ", au singulier ou au pluriel, il est écrit "PNJ", je pense qu'il faudrait harmoniser les deux termes)

**Comment by lecrapal** [comment]
J'ai regardé plusieurs bouquins, et PJ est écrit PJ que ce soit du singulier ou du pluriel.
Donc, il va falloir supprimer les "s" de PJ
