### ISSUE TITLE
Relique "Ami du Faucon" - sort de "Célérité"

### ISSUE THREAD

**Issue by brunobord** [lecrapal/lecrapal.github.io#5]
Dans la description des reliques :

```markdown
**Ami du Faucon**, 1 charge. Une baguette en forme d'éclair portant le sort _Célérité_. Recharge : tirer à l'arbalète et récupérer.
```

Le problème, c'est que le sort de "Célérité" n'apparaît pas dans la description des Sorts. Il semble dans la VO que le nom du sort est "Haste", qui a été traduit par "Hâte" dans la version traduite.

Il faudrait probablement choisir entre ces deux traductions et rendre cohérents le descriptif de la relique et le nom du sort dans la liste des 100 sorts.

**Comment by lecrapal** [comment]
Bonne remarque, du fait qu'on parle d'un sort, donc de magie, le terme Célérité me paraît plus approprié que Hâte, qui est en soit quelque chose de plus normal, moins surnaturelle.
